
import { Clinic } from './types';

// Mock data for fallback when API calls fail
export const getMockClinics = (): Clinic[] => [
  { 
    id: '1',
    name: 'Wellness Center',
    email: 'info@wellness.com',
    phone: '(555) 123-4567',
    status: 'active',
    createdAt: '2023-01-15T00:00:00.000Z',
    streetAddress: '123 Main St',
    city: 'New York',
    state: 'NY',
    zip: '10001',
    primaryContact: 'John Smith',
    billingContactName: 'Jane Smith',
    billingEmail: 'billing@wellness.com',
    billingPhone: '(555) 123-9999',
    billingAddress: '123 Main St',
    billingCity: 'New York',
    billingState: 'NY',
    billingZip: '10001',
    paymentMethod: 'Credit Card',
    subscriptionTier: 'Premium',
    subscriptionStatus: 'active'
  },
  { 
    id: '2',
    name: 'Practice Naturals',
    email: 'contact@practicenaturals.com',
    phone: '(555) 234-5678',
    status: 'active',
    createdAt: '2023-02-20T00:00:00.000Z',
    streetAddress: '456 Boulevard Ave',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90001',
    primaryContact: 'Jane Doe',
    billingContactName: 'Bob Johnson',
    billingEmail: 'billing@practicenaturals.com',
    billingPhone: '(555) 234-9999',
    billingAddress: '456 Boulevard Ave',
    billingCity: 'Los Angeles',
    billingState: 'CA',
    billingZip: '90001',
    paymentMethod: 'Bank Transfer',
    subscriptionTier: 'Standard',
    subscriptionStatus: 'active'
  },
  { 
    id: '3',
    name: 'Health Partners',
    email: 'support@healthpartners.com',
    phone: '(555) 345-6789',
    status: 'active',
    createdAt: '2023-03-05T00:00:00.000Z',
    streetAddress: '789 Health Way',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    primaryContact: 'Mike Johnson',
    billingContactName: 'Sarah Wilson',
    billingEmail: 'billing@healthpartners.com',
    billingPhone: '(555) 345-9999',
    billingAddress: '789 Health Way',
    billingCity: 'Chicago',
    billingState: 'IL',
    billingZip: '60601',
    paymentMethod: 'Credit Card',
    subscriptionTier: 'Basic',
    subscriptionStatus: 'active'
  }
];
